/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  userManagement: {
    profile: {
      View: () => import('#domains/user_management/profile/controllers/view.controller'),
    },
  },
}
